name: fitstackapp
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # state
  bloc: ^8.0.3
  shared_preferences: ^2.0.15

  # ui
  dot_navigation_bar: ^1.0.1+4
  lottie: ^1.3.0
  rive: ^0.8.4

  # fonts
  google_fonts: ^2.3.2
  font_awesome_flutter: ^10.1.0
  line_icons: ^2.0.1

  # Images
  flutter_svg: ^1.0.3

  # for debug
  device_preview: ^1.0.0

  # interatial
  health: ^3.4.4

  # routing
  auto_route: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/app/icons/
    - assets/app/images/
